
tasks:
  - before: cd ./services/barn
    init: yarn cache clean && yarn install --network-concurrency 1
    openIn: bottom
  - before: cd ./services/reaper
    init: yarn cache clean && yarn install --network-concurrency 1
    openIn: bottom
