version: '2.1'
services:

    postgres:
        image: timescale/timescaledb:1.2.0-pg11
        networks:
            - development
        ports:
            - ${PG_PORT-5053}:5432
        environment:
            POSTGRES_USER: ${PG_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
            POSTGRES_DB: ${PG_DATABASE:-postgres}
        volumes:
            - ${HUMBLE_DATA}/pg:/var/lib/postgresql/data
            - ${HUMBLE_BACKUP}:/backup
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "content", "-U", "rawb_content_user"]
            interval: 10s
            timeout: 10s
            retries: 10

    grafana:
        image: grafana/grafana:5.4.3
        networks:
            - development
        ports:
            - ${GRAFANA_PORT-5051}:3000
        environment:
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-grafana}
        volumes:
            - ${HUMBLE_DATA}/grafana:/var/lib/grafana


    barn:
        build:
            context: ./services/barn
            dockerfile: Dockerfile.dev
        depends_on:
            - postgres
        networks:
            - development
        ports:
            - ${SERVER_PORT:-5050}:8080
        environment:
            APP_ID: rapha-barn
            NODE_ENV: ${NODE_ENV:-development}
            BABEL_ENV: ${BABEL_ENV:-node}
            LOG_LEVEL: ${LOG_LEVEL:-info}
            PG_HOST: postgres
            PG_PORT: 5432
            PG_DATABASE: ${PG_DATABASE:-postgres}
            PG_USERNAME: ${PG_USERNAME:-postgres}
            PG_PASSWORD: ${PG_PASSWORD:-postgres}
            PG_MAX_CONN_ATTEMPTS: ${PG_MAX_CONN_ATTEMPTS:-10}
            PG_CONN_ATTEMPTS_DELAY: ${PG_CONN_ATTEMPTS_DELAY:-2500}
            SERVER_PORT: 8080
            GRAPHQL_MOUNT_POINT: ${GRAPHQL_MOUNT_POINT:-/api}
            REACT_SSR: ${REACT_SSR:-no}
            REACT_SSR_ENABLED: ${REACT_SSR_ENABLED:-no}
            REACT_SSR_USE_CACHE: ${REACT_SSR_USE_CACHE:-no}
            API_DEFAULT_TOKEN: ${API_TOKEN:-raphaDevToken}
            EXTENSIONS: ${BARN_EXTENSIONS:-}
        volumes:
            - ./services/barn/ssr:/usr/src/app/ssr
            - ./services/barn/src:/usr/src/app/src
            - ./services/barn/build:/usr/src/app/build
            - ./extensions/barn:/var/lib/rapha/extensions
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:dev:api" ]

    app:
        build:
            context: ./services/barn
            dockerfile: Dockerfile.dev
        networks:
            - development
        ports:
            - ${FRONTEND_PORT:-5052}:3000
        volumes:
            - ./services/barn/src:/usr/src/app/src
            - ./services/barn/build:/usr/src/app/build
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start" ]

    build:
        build:
            context: ./services/barn
            dockerfile: Dockerfile.dev
        volumes:
            - ./services/barn/src:/usr/src/app/src
            - ./services/barn/build:/usr/src/app/build
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "build" ]

    reaper:
        build:
            context: ./services/reaper
            dockerfile: Dockerfile.dev
        networks:
            - development
        environment:
            NODE_ENV: ${NODE_ENV:-development}
            BABEL_ENV: ${BABEL_ENV:-node}
            LOG_LEVEL: ${LOG_LEVEL:-verbose}
            API_ENDPOINT: ${API_ENDPOINT:-http://barn:8080/api}
            API_TOKEN: ${API_TOKEN:-raphaDevToken}
            HOST_NAME: ${HOST_NAME:-localhost}
            EXTENSIONS: ${REAPER_EXTENSIONS:-}
            METRIC_HOST_DISK_FILTER: ;;/;;
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - ./services/reaper/ssr:/usr/src/app/ssr
            - ./extensions/reaper:/var/lib/rapha/extensions
            - ./data/pg:/var/lib/rapha/fsize/rapha-pg
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:dev" ]
    
networks:
    development:
