version: '2.1'
services:

    postgres:
        image: timescale/timescaledb:1.2.0-pg11
        networks:
            - production
        environment:
            POSTGRES_USER: ${PG_USERNAME}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DATABASE}
        volumes:
            - ./data/pg:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "content", "-U", "rawb_content_user"]
            interval: 10s
            timeout: 10s
            retries: 10

    grafana:
        image: grafana/grafana:5.4.3
        networks:
            - production
        environment:
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
            GF_SERVER_ROOT_URL: http://grafana:3000/grafana/
        volumes:
            - ./data/grafana:/var/lib/grafana

    barn:
        image: pigtail/barn:${VERSION:-latest}
        networks:
            - production
        depends_on:
            - postgres
        environment:
            PG_HOST: postgres
            PG_PORT: 5432
            PG_DATABASE: ${PG_DATABASE}
            PG_USERNAME: ${PG_USERNAME}
            PG_PASSWORD: ${PG_PASSWORD}
            API_DEFAULT_TOKEN: ${API_TOKEN}

    reaper:
        image: pigtail/reaper:${VERSION:-latest}
        networks:
            - production
        environment:
            HOST_NAME: ${HOST_NAME}
            API_ENDPOINT: ${API_ENDPOINT}
            API_TOKEN: ${API_TOKEN}
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock

    proxy:
        image: pigtail/proxy:${VERSION:-latest}
        depends_on:
            - barn
            - grafana
            - postgres
        networks:
            - production
        environment:
            - BOARDS_ENABLED=${BOARDS_ENABLED}
            - BOARDS_TOKEN=${BOARDS_TOKEN}
        ports:
            - ${SERVER_PORT}:80

networks:
    production:
