{
 "title": "Overview1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "localhost,host1,host2" }
  ]
 },
 "panels": [
  {
   "title": "Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  (value->'used')::float / (value->'total')::float as usage\nFROM\n  metrics\nWHERE\n  metric = 'host-mem'\nAND host = '$host'\n"
    }
   ]
  },
  {
   "title": "General Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  metric AS metric,\n  value::float AS \"value\"\nFROM metrics\nWHERE\n  $__timeFilter(ctime) AND\n  metric = 'docker_cpu_percent_tot' AND\n  host = '$host'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  metric AS metric,\n  value::float AS \"value\"\nFROM metrics\nWHERE\n  $__timeFilter(ctime) AND\n  metric = 'docker_mem_usage_tot' AND\n  host = '$host'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Active Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nupdated_at,\nname,\n(meta->>'cpu_percent')::float AS \"cpu\",\n(meta->>'mem_usage')::float AS \"mem_usage\",\n(meta->>'mem_limit')::float AS \"mem_limit\"\nFROM containers\nWHERE updated_at > NOW() - INTERVAL '20s'\nAND meta->>'state' = 'running'\nAND host = '$host'\nORDER BY meta->>'cpu_percent' DESC"
    }
   ]
  },
  {
   "title": "Root Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  (value->'/'->>'used')::float / (value->'/'->>'total')::float as usage\nFROM\n  metrics\nWHERE\n  metric = 'host-disk'\nAND host = '$host'\n"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\nto_char(ctime, 'hh:mm:ss') as ctime,\ncontainer, message FROM logs\nWHERE host = '$host'\nORDER BY id desc\nLIMIT 100"
    }
   ]
  }
 ]
}