{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "localhost,host1,host2" }
  ]
 },
 "panels": [
  {
   "title": "General Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  metric AS metric,\n  value::float AS \"value\"\nFROM metrics\nWHERE\n  $__timeFilter(ctime) AND\n  metric = 'docker_cpu_percent_tot' AND\n  host = '$host'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  metric AS metric,\n  value::float AS \"value\"\nFROM metrics\nWHERE\n  $__timeFilter(ctime) AND\n  metric = 'docker_mem_usage_tot' AND\n  host = '$host'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Active Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nupdated_at,\nname,\nmeta->>'state' AS \"state\",\n(meta->>'cpu_percent')::float AS \"cpu\",\n(meta->>'mem_usage')::float AS \"mem_usage\",\n(meta->>'mem_limit')::float AS \"mem_limit\"\nFROM containers\nWHERE updated_at > NOW() - INTERVAL '20s'\nAND host = '$host'\nORDER BY meta->>'cpu_percent' DESC"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\nto_char(ctime, 'hh:mm:ss') as ctime,\ncontainer, message FROM logs\nWHERE host = '$host'\nORDER BY id desc\nLIMIT 100"
    }
   ]
  }
 ]
}